
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.card
{
/// <summary>
/// ECardQuality 配套数据（enum-table 自动生成）
/// </summary>
public sealed partial class CardQualityConf : Luban.BeanBase
{
    public CardQualityConf(ByteBuf _buf) 
    {
        Value = (card.ECardQuality)_buf.ReadInt();
        DisplayName = _buf.ReadString();
        IconPath = _buf.ReadString();
        SortOrder = _buf.ReadInt();
    }

    public static CardQualityConf DeserializeCardQualityConf(ByteBuf _buf)
    {
        return new card.CardQualityConf(_buf);
    }

    /// <summary>
    /// 枚举主键（enum-table 自动生成）
    /// </summary>
    public readonly card.ECardQuality Value;
    /// <summary>
    /// 显示名称
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// 图标路径
    /// </summary>
    public readonly string IconPath;
    /// <summary>
    /// 排序
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = -1478238059;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "value:" + Value + ","
        + "displayName:" + DisplayName + ","
        + "iconPath:" + IconPath + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

