
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.card
{ 
    /// <summary>
    /// 卡牌品质枚举配置
    /// </summary>
    public enum ECardQuality
    {
        /// <summary>
        /// 普通品质
        /// </summary>
        COMMON = 1,
        /// <summary>
        /// 稀有品质
        /// </summary>
        RARE = 2,
        /// <summary>
        /// 史诗品质
        /// </summary>
        EPIC = 3,
        /// <summary>
        /// 传奇品质
        /// </summary>
        LEGENDARY = 4,
    }

} 

