
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.card
{
/// <summary>
/// 卡牌品质枚举配置
/// </summary>
public partial class TbCardQuality
{
    private readonly System.Collections.Generic.Dictionary<card.ECardQuality, card.CardQualityConf> _dataMap;
    private readonly System.Collections.Generic.List<card.CardQualityConf> _dataList;
    
    public TbCardQuality(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<card.ECardQuality, card.CardQualityConf>(n);
        _dataList = new System.Collections.Generic.List<card.CardQualityConf>(n);
        for(int i = n ; i > 0 ; --i)
        {
            card.CardQualityConf _v;
            _v = global::cfg.card.CardQualityConf.DeserializeCardQualityConf(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Value, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<card.ECardQuality, card.CardQualityConf> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<card.CardQualityConf> DataList => _dataList;

    public card.CardQualityConf GetOrDefault(card.ECardQuality key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public card.CardQualityConf Get(card.ECardQuality key) => _dataMap[key];
    public card.CardQualityConf this[card.ECardQuality key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
namespace cfg.card
{
/// <summary>
/// ECardQuality 枚举扩展方法（由 enum-table 模式自动生成）
/// </summary>
public static partial class ECardQualityExtensions
{
    /// <summary>
    /// 获取 ECardQuality 枚举值对应的配置数据。
    /// </summary>
    public static card.CardQualityConf GetConf(this card.ECardQuality self, cfg.Tables tables)
        => tables.TbCardQuality.Get(self);

    /// <summary>
    /// 获取 ECardQuality 枚举值对应的配置数据，不存在时返回 <c>null</c>。
    /// </summary>
    public static card.CardQualityConf GetConfOrDefault(this card.ECardQuality self, cfg.Tables tables)
        => tables.TbCardQuality.GetOrDefault(self);
}
}

