
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    /// <summary>
    /// 卡牌品质枚举配置
    /// </summary>
    public card.TbCardQuality TbCardQuality {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbCardQuality = new card.TbCardQuality(loader("card_tbcardquality"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbCardQuality.ResolveRef(this);
    }
}

}
